---
title: "Self-assessment"
author: Lily
format: pdf
---
### Self-assessment 3

## What did I learn in three chapters?
- Collecting Data: How to gather data accurately and keep detailed records.
- Organizing Data: The importance of structuring data logically for easy access.
- Transforming Data: Techniques for modifying data to fit analysis needs, and the necessity of tracking these changes.
- It's so convenient to gather data and curate it. 

## What was challenging?
- Most Challenging: Transforming data, as it requires careful consideration to maintain integrity. 

- Literature Influence: Highlighted the importance of data integrity, shaping the - research towards methods ensuring data reliability.
This reflection emphasizes the progression in understanding and handling data comprehensively, pinpointing areas for further exploration and adjustment in research direction influenced by encountered challenges and literature insights.

## The most confusing:
Our current coding work is all carried out with the aid of materials provided by our teacher. Without the guidance from these materials, how can we independently complete a piece of code or conduct a research project on our own? If we lack the professor's input—such as code examples, forks, and various resources—how can we conduct research or manage a fork/curate by ourselves?





